name: Deploy API (Zero-Downtime)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Code ko bina delete kiye VM par copy karo (no downtime)
      - name: Copy code to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          # simple project hai, bas yeh files bhejni kaafi
          source: "server.js,package.json"
          target: "~/app"

      # Dependencies install + pm2 reload/start
      - name: Install deps & reload with pm2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd ~/app
            npm install --omit=dev
            if pm2 list | grep -q "varun-api"; then
              pm2 reload varun-api
            else
              pm2 start server.js --name varun-api
            fi
            pm2 save

