name: Deploy API

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            sudo fuser -k 80/tcp || true
            mkdir -p ~/app
            cd ~/app
            rm -rf *
            cat > server.js <<'EOF'
            const express = require("express");
            const app = express();
            const PORT = 80;
            app.get("/sayHello", (req, res) => {
              res.json({ message: "Hello User" });
            });
            app.listen(PORT, () => console.log("API running
