name: Deploy API

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            # Ensure app directory exists
            mkdir -p ~/app
            cd ~/app

            # Pull latest code
            git init
            git remote remove origin || true
            git remote add origin https://github.com/varungangwar/backend-api.git
            git fetch origin main
            git reset --hard origin/main

            # Install dependencies without deleting everything
            npm install

            # Use pm2 for zero-downtime restart
            if pm2 list | grep -q "varun-api"; then
              pm2 reload varun-api
            else
              pm2 start server.js --name varun-api --watch
            fi
            pm2 save

